package Main;


import Admistrativo.AltasAdministrativo;
import Admistrativo.BajasAdministrativo;
import Consultas.Busqueda;
import Consultas.Perfil;
import DatosPersonales.AltaDocente;
import DatosPersonales.DatosProfesionales;
import Alumnos.AltaAlumno;
import Alumnos.BajasAlumno;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * Menu principal
 */

/**
 *
 * @author saulcorona
 */
public class menuPrincipal extends javax.swing.JFrame {
    //Variables para conexion con base de datos
    public static final String URL = "jdbc:mysql://localhost:3306/proyectoSaul?zeroDateTimeBehavior=CONVERT_TO_NULL"; // Se accede al local host y se pone la base  a la que se quiere acceder
    public static final String usuario ="root"; // El usuario que por convención se usa root
    public static final String contraseña = ""; // Aqui se coloca la contraseña de MySQL server
    /**
     * Creates new form menuPrincipal
     */
    public menuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        conectarBase = new javax.swing.JButton();
        menuPrincipal = new javax.swing.JMenuBar();
        menuAdministrativo = new javax.swing.JMenu();
        admiAltas = new javax.swing.JMenuItem();
        admiBajas = new javax.swing.JMenuItem();
        admiConsultas = new javax.swing.JMenuItem();
        menuAlumnos = new javax.swing.JMenu();
        alumnoAltas = new javax.swing.JMenuItem();
        alumnoBajas = new javax.swing.JMenuItem();
        alumnoConsulta = new javax.swing.JMenuItem();
        menuEstudios = new javax.swing.JMenu();
        estudioPlan = new javax.swing.JMenuItem();
        menuDatosPersonales = new javax.swing.JMenu();
        datosAltaDocente = new javax.swing.JMenuItem();
        datosProfesionales = new javax.swing.JMenuItem();
        menuConsultas = new javax.swing.JMenu();
        consultaConsulta = new javax.swing.JMenuItem();
        menuPerfilProfesional = new javax.swing.JMenu();
        altaPerfilProfesional = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Escuela de especialidades clinicas");

        conectarBase.setText("Conectar base de datos");
        conectarBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conectarBaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(conectarBase)
                        .addGap(28, 28, 28)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(70, 70, 70)
                .addComponent(conectarBase)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        menuAdministrativo.setText("Administrativo");
        menuAdministrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAdministrativoActionPerformed(evt);
            }
        });

        admiAltas.setText("Altas");
        admiAltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admiAltasActionPerformed(evt);
            }
        });
        menuAdministrativo.add(admiAltas);

        admiBajas.setText("Bajas");
        admiBajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admiBajasActionPerformed(evt);
            }
        });
        menuAdministrativo.add(admiBajas);

        admiConsultas.setText("Consultas");
        menuAdministrativo.add(admiConsultas);

        menuPrincipal.add(menuAdministrativo);

        menuAlumnos.setText("Alumnos");

        alumnoAltas.setText("Altas");
        alumnoAltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alumnoAltasActionPerformed(evt);
            }
        });
        menuAlumnos.add(alumnoAltas);

        alumnoBajas.setText("Bajas");
        alumnoBajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alumnoBajasActionPerformed(evt);
            }
        });
        menuAlumnos.add(alumnoBajas);

        alumnoConsulta.setText("Colsultas");
        menuAlumnos.add(alumnoConsulta);

        menuPrincipal.add(menuAlumnos);

        menuEstudios.setText("Estudios");

        estudioPlan.setText("Plan de estudios");
        menuEstudios.add(estudioPlan);

        menuPrincipal.add(menuEstudios);

        menuDatosPersonales.setText("Datos personales");

        datosAltaDocente.setText("Alta docente");
        datosAltaDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datosAltaDocenteActionPerformed(evt);
            }
        });
        menuDatosPersonales.add(datosAltaDocente);

        datosProfesionales.setText("Alta datos profesionales");
        datosProfesionales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datosProfesionalesActionPerformed(evt);
            }
        });
        menuDatosPersonales.add(datosProfesionales);

        menuPrincipal.add(menuDatosPersonales);

        menuConsultas.setText("Consultas");

        consultaConsulta.setText("Consulta");
        consultaConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaConsultaActionPerformed(evt);
            }
        });
        menuConsultas.add(consultaConsulta);

        menuPrincipal.add(menuConsultas);

        menuPerfilProfesional.setText("Perfil Profesional");

        altaPerfilProfesional.setText("Altas");
        altaPerfilProfesional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaPerfilProfesionalActionPerformed(evt);
            }
        });
        menuPerfilProfesional.add(altaPerfilProfesional);

        menuPrincipal.add(menuPerfilProfesional);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultaConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaConsultaActionPerformed
        Busqueda busqueda = new Busqueda();
        busqueda.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_consultaConsultaActionPerformed

    private void menuAdministrativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdministrativoActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_menuAdministrativoActionPerformed

    private void admiAltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admiAltasActionPerformed
       AltasAdministrativo altas = new AltasAdministrativo();
       
       altas.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_admiAltasActionPerformed

    private void conectarBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conectarBaseActionPerformed
        Connection conexion =  getConnection();
        //Codigo para probar que si se establecio la conexion
        PreparedStatement ps;
        ResultSet rs;
        
        try {
            ps = conexion.prepareStatement("select * from proyectoSaul.administrativo");
            rs = ps.executeQuery();
            
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "RFC, " + rs.getString("no_empleado"));
            } else {
                JOptionPane.showMessageDialog(null, "No existen registros");
            }
            conexion.close();
        } catch(Exception ex){
            System.err.println("Error, " + ex);
        }
        
    }//GEN-LAST:event_conectarBaseActionPerformed

    private void datosAltaDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datosAltaDocenteActionPerformed

        AltaDocente alta = new AltaDocente();
        alta.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_datosAltaDocenteActionPerformed

    private void datosProfesionalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datosProfesionalesActionPerformed
        DatosProfesionales profesionales = new DatosProfesionales();
        profesionales.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_datosProfesionalesActionPerformed

    private void altaPerfilProfesionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaPerfilProfesionalActionPerformed
        // TODO add your handling code here:
        Perfil consulta = new Perfil();
        consulta.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_altaPerfilProfesionalActionPerformed

    private void alumnoAltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alumnoAltasActionPerformed
        // TODO add your handling code here:
        AltaAlumno alta = new AltaAlumno();
        alta.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_alumnoAltasActionPerformed

    private void admiBajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admiBajasActionPerformed
        // TODO add your handling code here:
        BajasAdministrativo bajas = new BajasAdministrativo();
        bajas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_admiBajasActionPerformed

    private void alumnoBajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alumnoBajasActionPerformed
        // TODO add your handling code here:
        BajasAlumno baja = new BajasAlumno();
        baja.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_alumnoBajasActionPerformed
    
    //Clase para establecer la conexión a la base de datos
    public Connection getConnection(){
        Connection conexion=null;
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            conexion = (Connection) DriverManager.getConnection(URL, usuario, contraseña );
            JOptionPane.showMessageDialog(null, "Conexion exitosa");
                    
        }catch(Exception ex){
            System.err.println("Error, " + ex);
            JOptionPane.showMessageDialog(null, "Error, " + ex);
        }
        
        return conexion;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem admiAltas;
    private javax.swing.JMenuItem admiBajas;
    private javax.swing.JMenuItem admiConsultas;
    private javax.swing.JMenuItem altaPerfilProfesional;
    private javax.swing.JMenuItem alumnoAltas;
    private javax.swing.JMenuItem alumnoBajas;
    private javax.swing.JMenuItem alumnoConsulta;
    private javax.swing.JButton conectarBase;
    private javax.swing.JMenuItem consultaConsulta;
    private javax.swing.JMenuItem datosAltaDocente;
    private javax.swing.JMenuItem datosProfesionales;
    private javax.swing.JMenuItem estudioPlan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuAdministrativo;
    private javax.swing.JMenu menuAlumnos;
    private javax.swing.JMenu menuConsultas;
    private javax.swing.JMenu menuDatosPersonales;
    private javax.swing.JMenu menuEstudios;
    private javax.swing.JMenu menuPerfilProfesional;
    private javax.swing.JMenuBar menuPrincipal;
    // End of variables declaration//GEN-END:variables
}
