/*
 * Altas administrativo
 */

package Admistrativo;

import Alumnos.AltaAlumno;
import Alumnos.BajasAlumno;
import Consultas.Perfil;
import Main.menuPrincipal;
import static Main.menuPrincipal.URL;
import static Main.menuPrincipal.contraseña;
import static Main.menuPrincipal.usuario;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author saulcorona
 */
public class AltasAdministrativo extends javax.swing.JFrame {
    
    //Variables para conexion con base de datos
    public static final String URL = "jdbc:mysql://localhost:3306/proyectoSaul?zeroDateTimeBehavior=CONVERT_TO_NULL"; // Se accede al local host y se pone la base  a la que se quiere acceder
    public static final String usuario ="root"; // El usuario que por convención se usa root
    public static final String contraseña = ""; // Aqui se coloca la contraseña de MySQL server
    PreparedStatement ps;
    ResultSet rs;
    
    public Connection getConnection(){
        Connection conexion=null;
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            conexion = (Connection) DriverManager.getConnection(URL, usuario, contraseña );
            //JOptionPane.showMessageDialog(null, "Conexion exitosa");
                    
        }catch(Exception ex){
            System.err.println("Error, " + ex);
            JOptionPane.showMessageDialog(null, "Error, " + ex);
        }
        
        return conexion;
    }
    
    /**
     * Metodo para limpiar el formualario
     */
    
    public void limpiarCajar(){
        altaRfc.setText(null);
        altaNoEmpleado.setText(null);
        altaArea.setText(null);
        altaPuesto.setText(null);
    }
    
    /**
     * Creates new form AltasAdministrativo
     */
    public AltasAdministrativo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        altaPuesto = new javax.swing.JTextField();
        altaRfc = new javax.swing.JTextField();
        altaNoEmpleado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        altaArea = new javax.swing.JTextField();
        salirAlta = new javax.swing.JButton();
        altasAdministrativoGuardar = new javax.swing.JButton();
        LimpiarAltaAdministrativo = new javax.swing.JButton();
        menuPrincipal = new javax.swing.JMenuBar();
        menuAdministrativo = new javax.swing.JMenu();
        admiAltas = new javax.swing.JMenuItem();
        admiBajas = new javax.swing.JMenuItem();
        admiConsultas = new javax.swing.JMenuItem();
        menuAlumnos = new javax.swing.JMenu();
        alumnoAltas = new javax.swing.JMenuItem();
        alumnoBajas = new javax.swing.JMenuItem();
        alumnoConsulta = new javax.swing.JMenuItem();
        menuEstudios = new javax.swing.JMenu();
        estudioPlan = new javax.swing.JMenuItem();
        menuDatosPersonales = new javax.swing.JMenu();
        datosDocente = new javax.swing.JMenuItem();
        datosProfesionales = new javax.swing.JMenuItem();
        menuConsultas = new javax.swing.JMenu();
        consultaConsulta = new javax.swing.JMenuItem();
        menuPerfilProfesional = new javax.swing.JMenu();
        altaPerfilProfesional = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Administrativo > altas");

        jLabel2.setText("RFC");

        jLabel3.setText("No empleado");

        jLabel4.setText("Area");

        jLabel6.setText("Puesto");

        altaArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaAreaActionPerformed(evt);
            }
        });

        salirAlta.setText("Salir");
        salirAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirAltaActionPerformed(evt);
            }
        });

        altasAdministrativoGuardar.setText("Altas");
        altasAdministrativoGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altasAdministrativoGuardarActionPerformed(evt);
            }
        });

        LimpiarAltaAdministrativo.setText("Limpiar");
        LimpiarAltaAdministrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarAltaAdministrativoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jLabel6)
                        .addComponent(jLabel4))
                    .addComponent(altasAdministrativoGuardar))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(altaArea, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(altaPuesto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(altaRfc, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(altaNoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LimpiarAltaAdministrativo)
                        .addGap(18, 18, 18)
                        .addComponent(salirAlta)))
                .addGap(201, 323, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(altaRfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(altaNoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(altaArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(altaPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salirAlta)
                    .addComponent(altasAdministrativoGuardar)
                    .addComponent(LimpiarAltaAdministrativo))
                .addContainerGap())
        );

        menuAdministrativo.setText("Administrativo");
        menuAdministrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAdministrativoActionPerformed(evt);
            }
        });

        admiAltas.setText("Altas");
        menuAdministrativo.add(admiAltas);

        admiBajas.setText("Bajas");
        admiBajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admiBajasActionPerformed(evt);
            }
        });
        menuAdministrativo.add(admiBajas);

        admiConsultas.setText("Consultas");
        menuAdministrativo.add(admiConsultas);

        menuPrincipal.add(menuAdministrativo);

        menuAlumnos.setText("Alumnos");

        alumnoAltas.setText("Altas");
        alumnoAltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alumnoAltasActionPerformed(evt);
            }
        });
        menuAlumnos.add(alumnoAltas);

        alumnoBajas.setText("Bajas");
        alumnoBajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alumnoBajasActionPerformed(evt);
            }
        });
        menuAlumnos.add(alumnoBajas);

        alumnoConsulta.setText("Colsultas");
        menuAlumnos.add(alumnoConsulta);

        menuPrincipal.add(menuAlumnos);

        menuEstudios.setText("Estudios");

        estudioPlan.setText("Plan de estudios");
        menuEstudios.add(estudioPlan);

        menuPrincipal.add(menuEstudios);

        menuDatosPersonales.setText("Datos personales");

        datosDocente.setText("Alta docente");
        menuDatosPersonales.add(datosDocente);

        datosProfesionales.setText("Alta datos profesionales");
        menuDatosPersonales.add(datosProfesionales);

        menuPrincipal.add(menuDatosPersonales);

        menuConsultas.setText("Consultas");

        consultaConsulta.setText("Consulta");
        consultaConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaConsultaActionPerformed(evt);
            }
        });
        menuConsultas.add(consultaConsulta);

        menuPrincipal.add(menuConsultas);

        menuPerfilProfesional.setText("Perfil Profesional");

        altaPerfilProfesional.setText("Altas");
        altaPerfilProfesional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaPerfilProfesionalActionPerformed(evt);
            }
        });
        menuPerfilProfesional.add(altaPerfilProfesional);

        menuPrincipal.add(menuPerfilProfesional);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAdministrativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdministrativoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_menuAdministrativoActionPerformed

    private void consultaConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultaConsultaActionPerformed

    private void altaAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_altaAreaActionPerformed

    private void salirAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirAltaActionPerformed
        menuPrincipal menu = new menuPrincipal();
        
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_salirAltaActionPerformed

    private void altasAdministrativoGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altasAdministrativoGuardarActionPerformed
        //Enviar información a la base de datos
        Connection conexion = null;
        
        try{
            conexion = getConnection();
            ps = conexion.prepareStatement("insert into proyectoSaul.administrativo (rfc,no_empleado,area,puesto) values(?,?,?,?)");
            ps.setString(1, altaRfc.getText());
            ps.setString(2, altaNoEmpleado.getText());
            ps.setString(3, altaArea.getText());
            ps.setString(4, altaPuesto.getText());
            
            int resultado = ps.executeUpdate(); //Ejecutamos la inserción en la base de datos
            
            if(resultado > 0) {
                JOptionPane.showMessageDialog(null, "Registro insertado correctamente");
                limpiarCajar();
            } else {
                JOptionPane.showMessageDialog(null, "Error al insertar el registro");
                limpiarCajar();
            }
            conexion.close();
        }catch(Exception ex){
            System.err.println("Error, "+ex);
        }
    }//GEN-LAST:event_altasAdministrativoGuardarActionPerformed

    private void altaPerfilProfesionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaPerfilProfesionalActionPerformed
        // Registrar perfil
        Perfil consulta = new Perfil();
        consulta.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_altaPerfilProfesionalActionPerformed

    private void LimpiarAltaAdministrativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarAltaAdministrativoActionPerformed
        // Limpiar caja
        limpiarCajar();
    }//GEN-LAST:event_LimpiarAltaAdministrativoActionPerformed

    private void admiBajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admiBajasActionPerformed
        // TODO add your handling code here:
        BajasAdministrativo bajas = new BajasAdministrativo();
        bajas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_admiBajasActionPerformed

    private void alumnoAltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alumnoAltasActionPerformed
        // TODO add your handling code here:
        AltaAlumno altas = new AltaAlumno();
        altas.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_alumnoAltasActionPerformed

    private void alumnoBajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alumnoBajasActionPerformed
        // TODO add your handling code here:
        BajasAlumno bajas = new BajasAlumno();
        bajas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_alumnoBajasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltasAdministrativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltasAdministrativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltasAdministrativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltasAdministrativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltasAdministrativo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LimpiarAltaAdministrativo;
    private javax.swing.JMenuItem admiAltas;
    private javax.swing.JMenuItem admiBajas;
    private javax.swing.JMenuItem admiConsultas;
    private javax.swing.JTextField altaArea;
    private javax.swing.JTextField altaNoEmpleado;
    private javax.swing.JMenuItem altaPerfilProfesional;
    private javax.swing.JTextField altaPuesto;
    private javax.swing.JTextField altaRfc;
    private javax.swing.JButton altasAdministrativoGuardar;
    private javax.swing.JMenuItem alumnoAltas;
    private javax.swing.JMenuItem alumnoBajas;
    private javax.swing.JMenuItem alumnoConsulta;
    private javax.swing.JMenuItem consultaConsulta;
    private javax.swing.JMenuItem datosDocente;
    private javax.swing.JMenuItem datosProfesionales;
    private javax.swing.JMenuItem estudioPlan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuAdministrativo;
    private javax.swing.JMenu menuAlumnos;
    private javax.swing.JMenu menuConsultas;
    private javax.swing.JMenu menuDatosPersonales;
    private javax.swing.JMenu menuEstudios;
    private javax.swing.JMenu menuPerfilProfesional;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JButton salirAlta;
    // End of variables declaration//GEN-END:variables
}
