/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admistrativo;

import Consultas.Perfil;
import Main.menuPrincipal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author saulcorona
 */
public class BajasAdministrativo extends javax.swing.JFrame {
    
    //Variables para conexion con base de datos
    public static final String URL = "jdbc:mysql://localhost:3306/proyectoSaul?zeroDateTimeBehavior=CONVERT_TO_NULL"; // Se accede al local host y se pone la base  a la que se quiere acceder
    public static final String usuario ="root"; // El usuario que por convención se usa root
    public static final String contraseña = ""; // Aqui se coloca la contraseña de MySQL server
    PreparedStatement ps;
    ResultSet rs;
    
    public Connection getConnection(){
        Connection conexion=null;
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            conexion = (Connection) DriverManager.getConnection(URL, usuario, contraseña );
            //JOptionPane.showMessageDialog(null, "Conexion exitosa");
                    
        }catch(Exception ex){
            System.err.println("Error, " + ex);
            JOptionPane.showMessageDialog(null, "Error, " + ex);
        }
        
        return conexion;
    }
    
     /**
     * Metodo para limpiar el formualario
     */
    
    public void limpiarCaja(){
        BuscarRFC.setText(null);
        cajaID.setText(null);
        RFCBajas.setText(null);
        NoEmpleadoBajas.setText(null);
        AreaBajas.setText(null);
        PuestoBajas.setText(null);
    }

    /**
     * Creates new form BajasAdministrativo
     */
    public BajasAdministrativo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BajasAdministrativoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BuscarRFC = new javax.swing.JTextField();
        LimpiarBajas = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        RFCBajas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        PuestoBajas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        AreaBajas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        NoEmpleadoBajas = new javax.swing.JTextField();
        EliminarBajas = new javax.swing.JButton();
        BuscarRFCBoton = new javax.swing.JButton();
        cajaID = new javax.swing.JTextField();
        salirBajas = new javax.swing.JButton();
        menuPrincipal = new javax.swing.JMenuBar();
        menuAdministrativo = new javax.swing.JMenu();
        admiAltas = new javax.swing.JMenuItem();
        admiBajas = new javax.swing.JMenuItem();
        admiConsultas = new javax.swing.JMenuItem();
        menuAlumnos = new javax.swing.JMenu();
        alumnoAltas = new javax.swing.JMenuItem();
        alumnoBajas = new javax.swing.JMenuItem();
        alumnoConsulta = new javax.swing.JMenuItem();
        menuEstudios = new javax.swing.JMenu();
        estudioPlan = new javax.swing.JMenuItem();
        menuDatosPersonales = new javax.swing.JMenu();
        datosDocente = new javax.swing.JMenuItem();
        datosProfesionales = new javax.swing.JMenuItem();
        menuConsultas = new javax.swing.JMenu();
        consultaConsulta = new javax.swing.JMenuItem();
        menuPerfilProfesional = new javax.swing.JMenu();
        altaPerfilProfesional = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BajasAdministrativoPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Administrativo > Bajas");

        jLabel2.setText("RFC");

        BuscarRFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarRFCActionPerformed(evt);
            }
        });

        LimpiarBajas.setText("Limpiar");
        LimpiarBajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarBajasActionPerformed(evt);
            }
        });

        jLabel3.setText("RFC");

        jLabel4.setText("No empleado");

        jLabel5.setText("Area");

        jLabel6.setText("Puesto");

        EliminarBajas.setText("Eliminar");
        EliminarBajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarBajasActionPerformed(evt);
            }
        });

        BuscarRFCBoton.setText("Buscar");
        BuscarRFCBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarRFCBotonActionPerformed(evt);
            }
        });

        cajaID.setBackground(new java.awt.Color(204, 204, 204));
        cajaID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaIDActionPerformed(evt);
            }
        });

        salirBajas.setText("Salir");
        salirBajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBajasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BajasAdministrativoPanelLayout = new javax.swing.GroupLayout(BajasAdministrativoPanel);
        BajasAdministrativoPanel.setLayout(BajasAdministrativoPanelLayout);
        BajasAdministrativoPanelLayout.setHorizontalGroup(
            BajasAdministrativoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BajasAdministrativoPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(BajasAdministrativoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BajasAdministrativoPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BuscarRFC, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BuscarRFCBoton)
                        .addGap(18, 18, 18)
                        .addComponent(cajaID, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(BajasAdministrativoPanelLayout.createSequentialGroup()
                        .addGroup(BajasAdministrativoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(BajasAdministrativoPanelLayout.createSequentialGroup()
                                .addGroup(BajasAdministrativoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BajasAdministrativoPanelLayout.createSequentialGroup()
                                        .addGroup(BajasAdministrativoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(BajasAdministrativoPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(RFCBajas, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(BajasAdministrativoPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(AreaBajas, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(83, 83, 83)
                                        .addGroup(BajasAdministrativoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel6))
                                        .addGap(28, 28, 28))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BajasAdministrativoPanelLayout.createSequentialGroup()
                                        .addComponent(EliminarBajas)
                                        .addGap(18, 18, 18)
                                        .addComponent(LimpiarBajas)
                                        .addGap(35, 35, 35)))
                                .addGroup(BajasAdministrativoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(salirBajas)
                                    .addComponent(NoEmpleadoBajas, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PuestoBajas, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(84, Short.MAX_VALUE))))
        );
        BajasAdministrativoPanelLayout.setVerticalGroup(
            BajasAdministrativoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BajasAdministrativoPanelLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(BajasAdministrativoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BajasAdministrativoPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(BajasAdministrativoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(BuscarRFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BuscarRFCBoton)
                            .addComponent(cajaID, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(BajasAdministrativoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(RFCBajas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(NoEmpleadoBajas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(BajasAdministrativoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(AreaBajas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(PuestoBajas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(83, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BajasAdministrativoPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(BajasAdministrativoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EliminarBajas)
                            .addComponent(LimpiarBajas)
                            .addComponent(salirBajas))
                        .addGap(17, 17, 17))))
        );

        menuAdministrativo.setText("Administrativo");
        menuAdministrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAdministrativoActionPerformed(evt);
            }
        });

        admiAltas.setText("Altas");
        admiAltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admiAltasActionPerformed(evt);
            }
        });
        menuAdministrativo.add(admiAltas);

        admiBajas.setText("Bajas");
        admiBajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admiBajasActionPerformed(evt);
            }
        });
        menuAdministrativo.add(admiBajas);

        admiConsultas.setText("Consultas");
        menuAdministrativo.add(admiConsultas);

        menuPrincipal.add(menuAdministrativo);

        menuAlumnos.setText("Alumnos");

        alumnoAltas.setText("Altas");
        menuAlumnos.add(alumnoAltas);

        alumnoBajas.setText("Bajas");
        menuAlumnos.add(alumnoBajas);

        alumnoConsulta.setText("Colsultas");
        menuAlumnos.add(alumnoConsulta);

        menuPrincipal.add(menuAlumnos);

        menuEstudios.setText("Estudios");

        estudioPlan.setText("Plan de estudios");
        menuEstudios.add(estudioPlan);

        menuPrincipal.add(menuEstudios);

        menuDatosPersonales.setText("Datos personales");

        datosDocente.setText("Alta docente");
        menuDatosPersonales.add(datosDocente);

        datosProfesionales.setText("Alta datos profesionales");
        menuDatosPersonales.add(datosProfesionales);

        menuPrincipal.add(menuDatosPersonales);

        menuConsultas.setText("Consultas");

        consultaConsulta.setText("Consulta");
        consultaConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaConsultaActionPerformed(evt);
            }
        });
        menuConsultas.add(consultaConsulta);

        menuPrincipal.add(menuConsultas);

        menuPerfilProfesional.setText("Perfil Profesional");

        altaPerfilProfesional.setText("Altas");
        altaPerfilProfesional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaPerfilProfesionalActionPerformed(evt);
            }
        });
        menuPerfilProfesional.add(altaPerfilProfesional);

        menuPrincipal.add(menuPerfilProfesional);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(BajasAdministrativoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BajasAdministrativoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAdministrativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdministrativoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAdministrativoActionPerformed

    private void consultaConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultaConsultaActionPerformed

    private void altaPerfilProfesionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaPerfilProfesionalActionPerformed
        // Registrar perfil
        Perfil consulta = new Perfil();
        consulta.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_altaPerfilProfesionalActionPerformed

    private void BuscarRFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarRFCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarRFCActionPerformed

    private void admiBajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admiBajasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admiBajasActionPerformed

    private void admiAltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admiAltasActionPerformed
        AltasAdministrativo altas = new AltasAdministrativo();
        altas.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_admiAltasActionPerformed

    private void BuscarRFCBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarRFCBotonActionPerformed
        // TODO add your handling code here:
        Connection conexion = null;
        
        try {
            conexion = getConnection();
            ps = conexion.prepareStatement("select * from proyectoSaul.administrativo where rfc=?");
            ps.setString(1, BuscarRFC.getText());
            rs = ps.executeQuery();
            
            if(rs.next()){
                cajaID.setText(String.valueOf(rs.getInt("id_RFC")));
                RFCBajas.setText(rs.getString("rfc"));
                NoEmpleadoBajas.setText(rs.getString("no_empleado"));
                AreaBajas.setText(rs.getString("area"));
                PuestoBajas.setText(rs.getString("puesto"));
            } else {
                JOptionPane.showMessageDialog(null, "No existe esa persona");
            }
            
            conexion.close();
        }catch(Exception ex){
            System.err.println("Error, "+ex);
        }
        
    }//GEN-LAST:event_BuscarRFCBotonActionPerformed

    private void cajaIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaIDActionPerformed

    private void LimpiarBajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarBajasActionPerformed
        // Limpiar cajas
        limpiarCaja();
    }//GEN-LAST:event_LimpiarBajasActionPerformed

    private void EliminarBajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarBajasActionPerformed
        // Se muestra dialogo para confirmar la eliminación del usuario
        
        int desicion = JOptionPane.showConfirmDialog(null, "¿Deseas eliminar este usuario?", "Eliminar", JOptionPane.WARNING_MESSAGE);
        
        if(desicion == JOptionPane.YES_OPTION){ //Si se acepta se ejecuta la eliminación
           Connection conexion = null;
        
        try {
            conexion = getConnection();
            ps = conexion.prepareStatement("delete from proyectoSaul.administrativo where rfc=?");
            ps.setString(1, RFCBajas.getText());
            
            String rfc = RFCBajas.getText();
            
            int resultado = ps.executeUpdate(); //ejecutamos la eliminacion
            
            if(resultado > 0){
                   JOptionPane.showMessageDialog(null, "Registro " + rfc + " eliminado correctamente");
                   limpiarCaja();
            } else {
                JOptionPane.showMessageDialog(null, "Error al eliminar el registro");
                limpiarCaja();
            }
            
            conexion.close();
        }
        catch(Exception ex){
            System.err.println("Error, "+ex);
        }
        } 
        
        if(desicion == JOptionPane.NO_OPTION){ // En el no, no se elimina el usuario
            JOptionPane.showMessageDialog(null, "No se elimino usuario");
        }
        
        if(desicion == JOptionPane.CANCEL_OPTION){ // En el cancel se limpia la pantalla
            JOptionPane.showMessageDialog(null, "Si quiere eliminar un usuario vuelva a hacer la busqueda");
            limpiarCaja();
        }
    }//GEN-LAST:event_EliminarBajasActionPerformed

    private void salirBajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBajasActionPerformed
         menuPrincipal menu = new menuPrincipal();
        
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_salirBajasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BajasAdministrativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BajasAdministrativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BajasAdministrativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BajasAdministrativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BajasAdministrativo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AreaBajas;
    private javax.swing.JPanel BajasAdministrativoPanel;
    private javax.swing.JTextField BuscarRFC;
    private javax.swing.JButton BuscarRFCBoton;
    private javax.swing.JButton EliminarBajas;
    private javax.swing.JButton LimpiarBajas;
    private javax.swing.JTextField NoEmpleadoBajas;
    private javax.swing.JTextField PuestoBajas;
    private javax.swing.JTextField RFCBajas;
    private javax.swing.JMenuItem admiAltas;
    private javax.swing.JMenuItem admiBajas;
    private javax.swing.JMenuItem admiConsultas;
    private javax.swing.JMenuItem altaPerfilProfesional;
    private javax.swing.JMenuItem alumnoAltas;
    private javax.swing.JMenuItem alumnoBajas;
    private javax.swing.JMenuItem alumnoConsulta;
    private javax.swing.JTextField cajaID;
    private javax.swing.JMenuItem consultaConsulta;
    private javax.swing.JMenuItem datosDocente;
    private javax.swing.JMenuItem datosProfesionales;
    private javax.swing.JMenuItem estudioPlan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu menuAdministrativo;
    private javax.swing.JMenu menuAlumnos;
    private javax.swing.JMenu menuConsultas;
    private javax.swing.JMenu menuDatosPersonales;
    private javax.swing.JMenu menuEstudios;
    private javax.swing.JMenu menuPerfilProfesional;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JButton salirBajas;
    // End of variables declaration//GEN-END:variables
}
