/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Alumnos;

import Admistrativo.AltasAdministrativo;
import Admistrativo.BajasAdministrativo;
import Consultas.Perfil;
import Main.menuPrincipal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author saulcorona
 */
public class BajasAlumno extends javax.swing.JFrame {
    
    //Variables para conexion con base de datos
    public static final String URL = "jdbc:mysql://localhost:3306/proyectoSaul?zeroDateTimeBehavior=CONVERT_TO_NULL"; // Se accede al local host y se pone la base  a la que se quiere acceder
    public static final String usuario ="root"; // El usuario que por convención se usa root
    public static final String contraseña = ""; // Aqui se coloca la contraseña de MySQL server
    PreparedStatement ps;
    ResultSet rs;
    
    public Connection getConnection(){
        Connection conexion=null;
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            conexion = (Connection) DriverManager.getConnection(URL, usuario, contraseña );
            //JOptionPane.showMessageDialog(null, "Conexion exitosa");
                    
        }catch(Exception ex){
            System.err.println("Error, " + ex);
            JOptionPane.showMessageDialog(null, "Error, " + ex);
        }
        
        return conexion;
    }
    
     /**
     * Metodo para limpiar el formualario
     */
    
    public void limpiarCaja(){
        CajaID.setText(null);
        NombreBajaAlumno.setText(null);
        TelefonoBajaAlumno.setText(null);
        DireccionBajaAlumno.setText(null);
        CurpBajaAlumno.setText(null);
        CorreoBajaAlumno.setText(null);
        DocumentoBajaAlumno.setText(null);
    }

    /**
     * Creates new form BajasAlumno
     */
    public BajasAlumno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CurpBaja = new javax.swing.JLabel();
        BuscarCurpAlumno = new javax.swing.JTextField();
        BuscarCurpBoton = new javax.swing.JButton();
        SalirAlumno = new javax.swing.JButton();
        EliminarAlumno = new javax.swing.JButton();
        LimpiarAlumno = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        DireccionBajaAlumno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TelefonoBajaAlumno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        NombreBajaAlumno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        DocumentoBajaAlumno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CorreoBajaAlumno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CurpBajaAlumno = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CajaID = new javax.swing.JTextField();
        menuPrincipal = new javax.swing.JMenuBar();
        menuAdministrativo = new javax.swing.JMenu();
        admiAltas = new javax.swing.JMenuItem();
        admiBajas = new javax.swing.JMenuItem();
        admiConsultas = new javax.swing.JMenuItem();
        menuAlumnos = new javax.swing.JMenu();
        alumnoAltas = new javax.swing.JMenuItem();
        alumnoBajas = new javax.swing.JMenuItem();
        alumnoConsulta = new javax.swing.JMenuItem();
        menuEstudios = new javax.swing.JMenu();
        estudioPlan = new javax.swing.JMenuItem();
        menuDatosPersonales = new javax.swing.JMenu();
        datosDocente = new javax.swing.JMenuItem();
        datosProfesionales = new javax.swing.JMenuItem();
        menuConsultas = new javax.swing.JMenu();
        consultaConsulta = new javax.swing.JMenuItem();
        menuPerfilProfesional = new javax.swing.JMenu();
        altaPerfilProfesional = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bajas > Alumno");

        CurpBaja.setText("CURP");

        BuscarCurpBoton.setText("Buscar");
        BuscarCurpBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarCurpBotonActionPerformed(evt);
            }
        });

        SalirAlumno.setText("Salir");
        SalirAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirAlumnoActionPerformed(evt);
            }
        });

        EliminarAlumno.setText("Eliminar");
        EliminarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarAlumnoActionPerformed(evt);
            }
        });

        LimpiarAlumno.setText("Limpiar");
        LimpiarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarAlumnoActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre");

        jLabel3.setText("Dirección");

        jLabel4.setText("Telefono");

        jLabel5.setText("CURP");

        jLabel6.setText("Correo");

        jLabel7.setText("Documento");

        jLabel8.setText("(No disponible)");

        CajaID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaIDActionPerformed(evt);
            }
        });

        menuAdministrativo.setText("Administrativo");
        menuAdministrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAdministrativoActionPerformed(evt);
            }
        });

        admiAltas.setText("Altas");
        admiAltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admiAltasActionPerformed(evt);
            }
        });
        menuAdministrativo.add(admiAltas);

        admiBajas.setText("Bajas");
        admiBajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admiBajasActionPerformed(evt);
            }
        });
        menuAdministrativo.add(admiBajas);

        admiConsultas.setText("Consultas");
        menuAdministrativo.add(admiConsultas);

        menuPrincipal.add(menuAdministrativo);

        menuAlumnos.setText("Alumnos");

        alumnoAltas.setText("Altas");
        alumnoAltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alumnoAltasActionPerformed(evt);
            }
        });
        menuAlumnos.add(alumnoAltas);

        alumnoBajas.setText("Bajas");
        menuAlumnos.add(alumnoBajas);

        alumnoConsulta.setText("Colsultas");
        menuAlumnos.add(alumnoConsulta);

        menuPrincipal.add(menuAlumnos);

        menuEstudios.setText("Estudios");

        estudioPlan.setText("Plan de estudios");
        menuEstudios.add(estudioPlan);

        menuPrincipal.add(menuEstudios);

        menuDatosPersonales.setText("Datos personales");

        datosDocente.setText("Alta docente");
        menuDatosPersonales.add(datosDocente);

        datosProfesionales.setText("Alta datos profesionales");
        menuDatosPersonales.add(datosProfesionales);

        menuPrincipal.add(menuDatosPersonales);

        menuConsultas.setText("Consultas");

        consultaConsulta.setText("Consulta");
        consultaConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaConsultaActionPerformed(evt);
            }
        });
        menuConsultas.add(consultaConsulta);

        menuPrincipal.add(menuConsultas);

        menuPerfilProfesional.setText("Perfil Profesional");

        altaPerfilProfesional.setText("Altas");
        altaPerfilProfesional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaPerfilProfesionalActionPerformed(evt);
            }
        });
        menuPerfilProfesional.add(altaPerfilProfesional);

        menuPrincipal.add(menuPerfilProfesional);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addComponent(CurpBaja)
                                .addGap(18, 18, 18)
                                .addComponent(BuscarCurpAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel6))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(CorreoBajaAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(DireccionBajaAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(NombreBajaAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel8)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(EliminarAlumno)
                                                .addGap(61, 61, 61)
                                                .addComponent(LimpiarAlumno)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(DocumentoBajaAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SalirAlumno)
                                    .addComponent(BuscarCurpBoton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                                .addComponent(CajaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TelefonoBajaAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CurpBajaAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CurpBaja)
                    .addComponent(BuscarCurpAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuscarCurpBoton)
                    .addComponent(CajaID, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TelefonoBajaAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(NombreBajaAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(DireccionBajaAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(CurpBajaAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CorreoBajaAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(DocumentoBajaAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalirAlumno)
                    .addComponent(LimpiarAlumno)
                    .addComponent(EliminarAlumno))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAdministrativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdministrativoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAdministrativoActionPerformed

    private void consultaConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultaConsultaActionPerformed

    private void altaPerfilProfesionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaPerfilProfesionalActionPerformed
        // TODO add your handling code here:
        Perfil consulta = new Perfil();
        consulta.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_altaPerfilProfesionalActionPerformed

    private void admiAltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admiAltasActionPerformed
       AltasAdministrativo altas = new AltasAdministrativo();
       altas.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_admiAltasActionPerformed

    private void CajaIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaIDActionPerformed

    private void BuscarCurpBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarCurpBotonActionPerformed
        // TODO add your handling code here:
           Connection conexion = null;
        
        try {
            conexion = getConnection();
            ps = conexion.prepareStatement("select * from proyectoSaul.alumnos where curp=?");
            ps.setString(1, BuscarCurpAlumno.getText());
            rs = ps.executeQuery();
            
            if(rs.next()){
                CajaID.setText(String.valueOf(rs.getInt("id_alumno")));
                NombreBajaAlumno.setText(rs.getString("nombre"));
                TelefonoBajaAlumno.setText(rs.getString("telefono"));
                DireccionBajaAlumno.setText(rs.getString("direccion"));
                CurpBajaAlumno.setText(rs.getString("curp"));
                CorreoBajaAlumno.setText(rs.getString("correo"));
                DocumentoBajaAlumno.setText(rs.getString("documento"));
            } else {
                JOptionPane.showMessageDialog(null, "No existe esa persona");
            }
            
            conexion.close();
        }catch(Exception ex){
            System.err.println("Error, "+ex);
        }
    }//GEN-LAST:event_BuscarCurpBotonActionPerformed

    private void LimpiarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarAlumnoActionPerformed
        // Limpiar cajas
        limpiarCaja();
    }//GEN-LAST:event_LimpiarAlumnoActionPerformed

    private void alumnoAltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alumnoAltasActionPerformed
        AltaAlumno alta = new AltaAlumno();
        alta.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_alumnoAltasActionPerformed

    private void SalirAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirAlumnoActionPerformed
         menuPrincipal menu = new menuPrincipal();
        
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SalirAlumnoActionPerformed

    private void admiBajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admiBajasActionPerformed
        BajasAdministrativo bajas = new BajasAdministrativo();
        bajas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_admiBajasActionPerformed

    private void EliminarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarAlumnoActionPerformed
        // Se muestra dialogo para confirmar la eliminación del alumno
        int desicion = JOptionPane.showConfirmDialog(null, "¿Deseas eliminar este alumno?", "Eliminar", JOptionPane.WARNING_MESSAGE);
        
        if(desicion == JOptionPane.YES_OPTION){ // Si se acepta se ejecuta la eliminación 
            Connection conexion = null;
            
            try{
                conexion = getConnection();
                 ps = conexion.prepareStatement("delete from proyectoSaul.alumnos where curp=?");
                 ps.setString(1, CurpBajaAlumno.getText());
                 
                  String curp = CurpBajaAlumno.getText();
                  
                  int resultado = ps.executeUpdate(); //ejecutamos la eliminacion
                  
                  if(resultado > 0){
                    JOptionPane.showMessageDialog(null, "Registro " + curp + " eliminado correctamente");
                    limpiarCaja();
                    } else {
                        JOptionPane.showMessageDialog(null, "Error al eliminar el registro");
                        limpiarCaja();
                    }
            }catch(Exception ex){
                System.err.println("Error, "+ex);
            }
        }
        
        if(desicion == JOptionPane.NO_OPTION){ // En el no, no se elimina el usuario
            JOptionPane.showMessageDialog(null, "No se elimino el alumno");
        }
        
        if(desicion == JOptionPane.CANCEL_OPTION){ // En el cancel se limpia la pantalla
            JOptionPane.showMessageDialog(null, "Si quiere eliminar un alumno vuelva a hacer la busqueda");
            limpiarCaja();
        }
        
    }//GEN-LAST:event_EliminarAlumnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BajasAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BajasAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BajasAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BajasAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BajasAlumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BuscarCurpAlumno;
    private javax.swing.JButton BuscarCurpBoton;
    private javax.swing.JTextField CajaID;
    private javax.swing.JTextField CorreoBajaAlumno;
    private javax.swing.JLabel CurpBaja;
    private javax.swing.JTextField CurpBajaAlumno;
    private javax.swing.JTextField DireccionBajaAlumno;
    private javax.swing.JTextField DocumentoBajaAlumno;
    private javax.swing.JButton EliminarAlumno;
    private javax.swing.JButton LimpiarAlumno;
    private javax.swing.JTextField NombreBajaAlumno;
    private javax.swing.JButton SalirAlumno;
    private javax.swing.JTextField TelefonoBajaAlumno;
    private javax.swing.JMenuItem admiAltas;
    private javax.swing.JMenuItem admiBajas;
    private javax.swing.JMenuItem admiConsultas;
    private javax.swing.JMenuItem altaPerfilProfesional;
    private javax.swing.JMenuItem alumnoAltas;
    private javax.swing.JMenuItem alumnoBajas;
    private javax.swing.JMenuItem alumnoConsulta;
    private javax.swing.JMenuItem consultaConsulta;
    private javax.swing.JMenuItem datosDocente;
    private javax.swing.JMenuItem datosProfesionales;
    private javax.swing.JMenuItem estudioPlan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu menuAdministrativo;
    private javax.swing.JMenu menuAlumnos;
    private javax.swing.JMenu menuConsultas;
    private javax.swing.JMenu menuDatosPersonales;
    private javax.swing.JMenu menuEstudios;
    private javax.swing.JMenu menuPerfilProfesional;
    private javax.swing.JMenuBar menuPrincipal;
    // End of variables declaration//GEN-END:variables
}
